### ISSUE TITLE
Beta Testings: v8.0.0

### ISSUE THREAD

**Issue by donavanbecker** [homebridge-plugins/homebridge-resideo#231]
Looking to release `v8.0.0` of `homebridge-honeywell-home`. Looking for Beta testers.

To Install:
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```
To Revert: 
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@latest
```

**Comment by leemcx** [comment]
When installed, this shows up as homebridge-honeywell-home v7.2.1-beta.6 in the homebridge-config-ui.
This is the first version of homebridge-honeywell-home that has worked with my Honeywell T6R.
The 'heat' option in the homekit ui is not functioning but the 'auto' function is working. 
Glad to have a solution that partially works as the native homekit support is highly unreliable on this device.

**Comment by donavanbecker** [comment]
Can you post: your device info? By manually setting ```"devicediscovery": true``` in your config it will output a lot of info on your device that can help me better understand all the devices out there.

**Comment by leemcx** [comment]
Hope this helps: 

```
[9/8/2020, 10:22:02] Loaded plugin: homebridge-honeywell-home@7.2.1-beta.6
[9/8/2020, 10:22:02] Registering platform 'homebridge-honeywell-home.HoneywellHome'
[9/8/2020, 10:22:08] [HoneywellHome] Initializing HoneywellHome platform...
[9/8/2020, 10:22:08] [HoneywellHome] Finished initializing platform: HoneywellHome
[9/8/2020, 10:22:08] [HoneywellHome] Config OK
[9/8/2020, 10:22:09] [HoneywellHome] Loading accessory from cache: Thermostat Thermostat
[9/8/2020, 10:22:09] [HoneywellHome] Executed didFinishLaunching callback
[9/8/2020, 10:22:11] [HoneywellHome] Got access token: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
[9/8/2020, 10:22:11] [HoneywellHome] New refresh token: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
[9/8/2020, 10:22:11] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[9/8/2020, 10:22:12] [HoneywellHome] Total Locations Found: 1
[9/8/2020, 10:22:12] [HoneywellHome] Getting devices for Home...
[9/8/2020, 10:22:12] [HoneywellHome] Total Devices Found at Home: 1
[9/8/2020, 10:22:12] [HoneywellHome] {"displayedOutdoorHumidity":82,"vacationHold":{"enabled":false},"currentSchedulePeriod":{"day":"Monday","period":"P2"},"scheduleCapabilities":{"availableScheduleTypes":["None","Geofenced","TimedEmea"],"schedulableFan":false},"scheduleType":{"scheduleType":"Timed","scheduleSubType":"EMEA"},"scheduleStatus":"Pause","allowedTimeIncrements":10,"settings":{"hardwareSettings":{"brightness":4,"maxBrightness":5},"temperatureMode":{"air":false},"specialMode":{},"devicePairingEnabled":true},"deviceClass":"Thermostat","deviceType":"Thermostat","deviceID":"LCC-XXXXXXXXXXXX","userDefinedDeviceName":"Thermostat","name":"Thermostat","isAlive":true,"isUpgrading":false,"isProvisioned":true,"macID":"XXXXXXXXXXXX","deviceSettings":{},"service":{"mode":"Up"},"deviceRegistrationDate":"2020-09-03T09:35:13.17","dataSyncStatus":"Completed","units":"Celsius","indoorTemperature":19.5,"outdoorTemperature":18.5,"allowedModes":["Heat","Off"],"deadband":0,"hasDualSetpointStatus":false,"minHeatSetpoint":5,"maxHeatSetpoint":23,"minCoolSetpoint":-18,"maxCoolSetpoint":-18,"changeableValues":{"mode":"Heat","heatSetpoint":16.5,"coolSetpoint":17,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null},"operationStatus":{"mode":"EquipmentOff","fanRequest":false,"circulationFanRequest":false},"deviceModel":"T5-T6"}
[9/8/2020, 10:22:12] [HoneywellHome] "LCC-XXXXXXXXXXXX"
[9/8/2020, 10:22:12] [HoneywellHome] Device ID: LCC-XXXXXXXXXXXX
[9/8/2020, 10:22:12] [HoneywellHome] "Thermostat"
[9/8/2020, 10:22:12] [HoneywellHome] Device Type: Thermostat
[9/8/2020, 10:22:12] [HoneywellHome] "Thermostat"
[9/8/2020, 10:22:12] [HoneywellHome] Device Class: Thermostat
[9/8/2020, 10:22:12] [HoneywellHome] "T5-T6"
[9/8/2020, 10:22:12] [HoneywellHome] Device Model: T5-T6
[9/8/2020, 10:22:12] [HoneywellHome] {"hardwareSettings":{"brightness":4,"maxBrightness":5},"temperatureMode":{"air":false},"specialMode":{},"devicePairingEnabled":true}
[9/8/2020, 10:22:12] [HoneywellHome] Device Settings: [object Object]
[9/8/2020, 10:22:12] [HoneywellHome] Restoring existing accessory from cache: Thermostat Thermostat
[9/8/2020, 10:22:12] [HoneywellHome] T5 UDID: Thermostat-LCC-XXXXXXXXXXXX-T5-T6
[9/8/2020, 10:22:13] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":16.5,"coolSetpoint":17,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/8/2020, 10:22:13] [HoneywellHome] "Heat"
[9/8/2020, 10:22:24] [HoneywellHome] Set TargetHeatingCoolingState: 3
[9/8/2020, 10:22:24] [HoneywellHome] Sending request to Honeywell API. mode: Auto, coolSetpoint: 17, heatSetpoint: 16.5
[9/8/2020, 10:22:24] [HoneywellHome] {"mode":"Auto","thermostatSetpointStatus":"TemporaryHold","coolSetpoint":17,"heatSetpoint":16.5}
[9/8/2020, 10:22:24] [HoneywellHome] Set TargetHeatingCoolingState: 1
[9/8/2020, 10:22:24] [HoneywellHome] Sending request to Honeywell API. mode: Heat, coolSetpoint: 17, heatSetpoint: 16.5
[9/8/2020, 10:22:24] [HoneywellHome] {"mode":"Heat","thermostatSetpointStatus":"TemporaryHold","heatSetpoint":16.5,"coolSetpoint":17}
[9/8/2020, 10:22:26] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":16.5,"coolSetpoint":17,"thermostatSetpointStatus":"TemporaryHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/8/2020, 10:22:26] [HoneywellHome] "Heat"
[9/8/2020, 10:22:26] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":16.5,"coolSetpoint":17,"thermostatSetpointStatus":"TemporaryHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/8/2020, 10:22:26] [HoneywellHome] "Heat"
[9/8/2020, 10:22:37] [HoneywellHome] Set TargetHeatingCoolingState: 1
[9/8/2020, 10:22:37] [HoneywellHome] Sending request to Honeywell API. mode: Heat, coolSetpoint: 17, heatSetpoint: 16.5
[9/8/2020, 10:22:37] [HoneywellHome] {"mode":"Heat","thermostatSetpointStatus":"TemporaryHold","heatSetpoint":16.5,"coolSetpoint":17}
[9/8/2020, 10:22:39] [HoneywellHome] Set TargetHeatingCoolingState: 3
[9/8/2020, 10:22:39] [HoneywellHome] Sending request to Honeywell API. mode: Auto, coolSetpoint: 17, heatSetpoint: 16.5
[9/8/2020, 10:22:39] [HoneywellHome] {"mode":"Auto","thermostatSetpointStatus":"TemporaryHold","coolSetpoint":17,"heatSetpoint":16.5}
[9/8/2020, 10:22:39] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":16.5,"coolSetpoint":17,"thermostatSetpointStatus":"TemporaryHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/8/2020, 10:22:39] [HoneywellHome] "Heat"
[9/8/2020, 10:22:41] [HoneywellHome] Set TargetHeatingCoolingState: 1
[9/8/2020, 10:22:41] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Auto","heatSetpoint":16.5,"coolSetpoint":17,"thermostatSetpointStatus":"TemporaryHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/8/2020, 10:22:41] [HoneywellHome] "Auto"
[9/8/2020, 10:22:41] [HoneywellHome] Sending request to Honeywell API. mode: Auto, coolSetpoint: 17, heatSetpoint: 16.5
[9/8/2020, 10:22:41] [HoneywellHome] {"mode":"Auto","thermostatSetpointStatus":"TemporaryHold","coolSetpoint":17,"heatSetpoint":16.5}
[9/8/2020, 10:22:43] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Auto","heatSetpoint":16.5,"coolSetpoint":17,"thermostatSetpointStatus":"TemporaryHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/8/2020, 10:22:43] [HoneywellHome] "Auto"
[9/8/2020, 10:23:12] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":16.5,"coolSetpoint":17,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
```

**Comment by donavanbecker** [comment]
@leemcx can you try `v7.2.2-beta.0`

**Comment by leemcx** [comment]
@donavanbecker v7.2.2-beta.0 works perfectly with the T6R. The issue described in the above post has now been resolved. Thank you. 

Quick question, since I don’t have the hardware to support the ‘COOL’ and ‘AUTO’ function displayed on the thermostat ui in HomeKit, is there a way to disable it? It’s purely cosmetic, I’m aware of that.

**Comment by donavanbecker** [comment]
I believe so, let me check.

**Comment by donavanbecker** [comment]
@leemcx, so with the latest beta, I pushed a potential fix for this. can you test it for me? My device supports `['Off','Heat','Cool','Auto']` so I can't test this. `v7.2.2-beta.3`

**Comment by leemcx** [comment]
@donavanbecker. When installed, this shows up as homebridge-honeywell-home v7.2.2-beta.4, the COOL and AUTO options in the HomeKit ui are still present.

**Comment by donavanbecker** [comment]
Thanks for trying, it was worth a shot. Have one other idea. I will let you know when I have a new beta out.

**Comment by donavanbecker** [comment]
@leemcx okay can you give the new beta a try and report back? `v7.2.2-beta.6`

**Comment by leemcx** [comment]
@donavanbecker, it appears the COOL and AUTO modes are still present in this beta. Could any caching being taking place?

**Comment by donavanbecker** [comment]
@leemcx Can you turn on devicediscovery on and debug mode?

Go to config and add `devicediscovery: true` and post what it logs?

**Comment by leemcx** [comment]
hope this helps:

```
[9/11/2020, 19:22:21] [HoneywellHome] Initializing HoneywellHome platform...
[9/11/2020, 19:22:21] [HoneywellHome] Finished initializing platform: HoneywellHome
[9/11/2020, 19:22:21] [HoneywellHome] Room Sensors will only display as Room Sensors.
[9/11/2020, 19:22:21] [HoneywellHome] Config OK
[9/11/2020, 19:22:23] [HoneywellHome] Got access token: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
[9/11/2020, 19:22:23] [HoneywellHome] New refresh token: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
[9/11/2020, 19:22:23] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[9/11/2020, 19:22:25] [HoneywellHome] Total Locations Found: 1
[9/11/2020, 19:22:25] [HoneywellHome] Getting devices for Home...
[9/11/2020, 19:22:25] [HoneywellHome] Total Devices Found at Home: 1
[9/11/2020, 19:22:25] [HoneywellHome] "LCC-XXXXXXXXXXXX”
[9/11/2020, 19:22:25] [HoneywellHome] Device ID: LCC-XXXXXXXXXXXX
[9/11/2020, 19:22:25] [HoneywellHome] "Thermostat"
[9/11/2020, 19:22:25] [HoneywellHome] Device Type: Thermostat
[9/11/2020, 19:22:25] [HoneywellHome] "Thermostat"
[9/11/2020, 19:22:25] [HoneywellHome] Device Class: Thermostat
[9/11/2020, 19:22:25] [HoneywellHome] "T5-T6"
[9/11/2020, 19:22:25] [HoneywellHome] Device Model: T5-T6
[9/11/2020, 19:22:25] [HoneywellHome] {"hardwareSettings":{"brightness":4,"maxBrightness":5},"temperatureMode":{"air":false},"specialMode":{},"devicePairingEnabled":true}
[9/11/2020, 19:22:25] [HoneywellHome] {"displayedOutdoorHumidity":66,"vacationHold":{"enabled":false},"currentSchedulePeriod":{"day":"Monday","period":"P5"},"scheduleCapabilities":{"availableScheduleTypes":["None","Geofenced","TimedEmea"],"schedulableFan":false},"scheduleType":{"scheduleType":"Timed","scheduleSubType":"EMEA"},"scheduleStatus":"Pause","allowedTimeIncrements":10,"settings":{"hardwareSettings":{"brightness":4,"maxBrightness":5},"temperatureMode":{"air":false},"specialMode":{},"devicePairingEnabled":true},"deviceClass":"Thermostat","deviceType":"Thermostat","deviceID":"LCC-B82CA041BD20","userDefinedDeviceName":"Thermostat","name":"Thermostat","isAlive":true,"isUpgrading":false,"isProvisioned":true,"macID":"B82CA041BD20","deviceSettings":{},"service":{"mode":"Up"},"deviceRegistrationDate":"2020-09-03T09:35:13.17","dataSyncStatus":"Completed","units":"Celsius","indoorTemperature":20,"outdoorTemperature":15.5,"allowedModes":["Heat","Off"],"deadband":0,"hasDualSetpointStatus":false,"minHeatSetpoint":5,"maxHeatSetpoint":23,"minCoolSetpoint":-18,"maxCoolSetpoint":-18,"changeableValues":{"mode":"Heat","heatSetpoint":20,"coolSetpoint":20,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null},"operationStatus":{"mode":"EquipmentOff","fanRequest":false,"circulationFanRequest":false},"deviceModel":"T5-T6"}
[9/11/2020, 19:22:25] [HoneywellHome] Restoring existing accessory from cache: Thermostat Thermostat
[9/11/2020, 19:22:25] [HoneywellHome] Device is in "Heat" mode
[9/11/2020, 19:22:25] [HoneywellHome] T5 UDID: Thermostat-LCC-XXXXXXXXXXXX-T5-T6
[9/11/2020, 19:22:26] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":20,"coolSetpoint":20,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/11/2020, 19:22:26] [HoneywellHome] {"displayedOutdoorHumidity":66,"vacationHold":{"enabled":false},"currentSchedulePeriod":{"day":"Monday","period":"P5"},"scheduleCapabilities":{"availableScheduleTypes":["None","Geofenced","TimedEmea"],"schedulableFan":false},"scheduleType":{"scheduleType":"Timed","scheduleSubType":"EMEA"},"scheduleStatus":"Pause","allowedTimeIncrements":10,"settings":{"hardwareSettings":{"brightness":4,"maxBrightness":5},"temperatureMode":{"air":false},"specialMode":{},"devicePairingEnabled":true},"deviceClass":"Thermostat","deviceType":"Thermostat","deviceID":"LCC-B82CA041BD20","userDefinedDeviceName":"Thermostat","name":"Thermostat","isAlive":true,"isUpgrading":false,"isProvisioned":true,"macID":"B82CA041BD20","deviceSettings":{},"service":{"mode":"Up"},"deviceRegistrationDate":"2020-09-03T09:35:13.17","dataSyncStatus":"Completed","units":"Celsius","indoorTemperature":20,"outdoorTemperature":15.5,"allowedModes":["Heat","Off"],"deadband":0,"hasDualSetpointStatus":false,"minHeatSetpoint":5,"maxHeatSetpoint":23,"minCoolSetpoint":-18,"maxCoolSetpoint":-18,"changeableValues":{"mode":"Heat","heatSetpoint":20,"coolSetpoint":20,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null},"operationStatus":{"mode":"EquipmentOff","fanRequest":false,"circulationFanRequest":false},"deviceModel":"T5-T6"}
[9/11/2020, 19:23:26] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":20,"coolSetpoint":20,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/11/2020, 19:23:26] [HoneywellHome] {"displayedOutdoorHumidity":66,"vacationHold":{"enabled":false},"currentSchedulePeriod":{"day":"Monday","period":"P5"},"scheduleCapabilities":{"availableScheduleTypes":["None","Geofenced","TimedEmea"],"schedulableFan":false},"scheduleType":{"scheduleType":"Timed","scheduleSubType":"EMEA"},"scheduleStatus":"Pause","allowedTimeIncrements":10,"settings":{"hardwareSettings":{"brightness":4,"maxBrightness":5},"temperatureMode":{"air":false},"specialMode":{},"devicePairingEnabled":true},"deviceClass":"Thermostat","deviceType":"Thermostat","deviceID":"LCC-B82CA041BD20","userDefinedDeviceName":"Thermostat","name":"Thermostat","isAlive":true,"isUpgrading":false,"isProvisioned":true,"macID":"B82CA041BD20","deviceSettings":{},"service":{"mode":"Up"},"deviceRegistrationDate":"2020-09-03T09:35:13.17","dataSyncStatus":"Completed","units":"Celsius","indoorTemperature":20,"outdoorTemperature":15.5,"allowedModes":["Heat","Off"],"deadband":0,"hasDualSetpointStatus":false,"minHeatSetpoint":5,"maxHeatSetpoint":23,"minCoolSetpoint":-18,"maxCoolSetpoint":-18,"changeableValues":{"mode":"Heat","heatSetpoint":20,"coolSetpoint":20,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null},"operationStatus":{"mode":"EquipmentOff","fanRequest":false,"circulationFanRequest":false},"deviceModel":"T5-T6"}
[9/11/2020, 19:23:30] [HoneywellHome] Set TargetHeatingCoolingState: 1
[9/11/2020, 19:23:30] [HoneywellHome] Sending request to Honeywell API. mode: Heat, coolSetpoint: 20, heatSetpoint: 20
[9/11/2020, 19:23:30] [HoneywellHome] {"mode":"Heat","thermostatSetpointStatus":"TemporaryHold","heatSetpoint":20,"coolSetpoint":20}
[9/11/2020, 19:23:32] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":20,"coolSetpoint":20,"thermostatSetpointStatus":"TemporaryHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/11/2020, 19:23:32] [HoneywellHome] {"displayedOutdoorHumidity":66,"vacationHold":{"enabled":false},"currentSchedulePeriod":{"day":"Monday","period":"P5"},"scheduleCapabilities":{"availableScheduleTypes":["None","Geofenced","TimedEmea"],"schedulableFan":false},"scheduleType":{"scheduleType":"Timed","scheduleSubType":"EMEA"},"scheduleStatus":"Pause","allowedTimeIncrements":10,"settings":{"hardwareSettings":{"brightness":4,"maxBrightness":5},"temperatureMode":{"air":false},"specialMode":{},"devicePairingEnabled":true},"deviceClass":"Thermostat","deviceType":"Thermostat","deviceID":"LCC-B82CA041BD20","userDefinedDeviceName":"Thermostat","name":"Thermostat","isAlive":true,"isUpgrading":false,"isProvisioned":true,"macID":"B82CA041BD20","deviceSettings":{},"service":{"mode":"Up"},"deviceRegistrationDate":"2020-09-03T09:35:13.17","dataSyncStatus":"Completed","units":"Celsius","indoorTemperature":20,"outdoorTemperature":15.5,"allowedModes":["Heat","Off"],"deadband":0,"hasDualSetpointStatus":false,"minHeatSetpoint":5,"maxHeatSetpoint":23,"minCoolSetpoint":-18,"maxCoolSetpoint":-18,"changeableValues":{"mode":"Heat","heatSetpoint":20,"coolSetpoint":20,"thermostatSetpointStatus":"TemporaryHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null},"operationStatus":{"mode":"EquipmentOff","fanRequest":false,"circulationFanRequest":false},"deviceModel":"T5-T6"}
[9/11/2020, 19:24:26] [HoneywellHome] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":20,"coolSetpoint":20,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null}
[9/11/2020, 19:24:26] [HoneywellHome] {"displayedOutdoorHumidity":66,"vacationHold":{"enabled":false},"currentSchedulePeriod":{"day":"Monday","period":"P5"},"scheduleCapabilities":{"availableScheduleTypes":["None","Geofenced","TimedEmea"],"schedulableFan":false},"scheduleType":{"scheduleType":"Timed","scheduleSubType":"EMEA"},"scheduleStatus":"Pause","allowedTimeIncrements":10,"settings":{"hardwareSettings":{"brightness":4,"maxBrightness":5},"temperatureMode":{"air":false},"specialMode":{},"devicePairingEnabled":true},"deviceClass":"Thermostat","deviceType":"Thermostat","deviceID":"LCC-B82CA041BD20","userDefinedDeviceName":"Thermostat","name":"Thermostat","isAlive":true,"isUpgrading":false,"isProvisioned":true,"macID":"B82CA041BD20","deviceSettings":{},"service":{"mode":"Up"},"deviceRegistrationDate":"2020-09-03T09:35:13.17","dataSyncStatus":"Completed","units":"Celsius","indoorTemperature":20,"outdoorTemperature":15.5,"allowedModes":["Heat","Off"],"deadband":0,"hasDualSetpointStatus":false,"minHeatSetpoint":5,"maxHeatSetpoint":23,"minCoolSetpoint":-18,"maxCoolSetpoint":-18,"changeableValues":{"mode":"Heat","heatSetpoint":20,"coolSetpoint":20,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null},"operationStatus":{"mode":"EquipmentOff","fanRequest":false,"circulationFanRequest":false},"deviceModel":"T5-T6"}
```

**Comment by donavanbecker** [comment]
@leemcx, beta `v7.2.2-beta.11` should definitely work for you. Please report back. You should only see Heat and Off.

**Comment by leemcx** [comment]
@donavanbecker, the barrel menu that allowed for the mode selection has now been removed and replaced with a button. The button does not turn off the device as you would expect but rather it selects `AUTO` mode. Please see link to image. 

https://imgur.com/gallery/9Ap8OBF

**Comment by donavanbecker** [comment]
What if you restart or clear cache?

**Comment by donavanbecker** [comment]
Wow for some reason I must of got it mixed up. push a new beta `v7.2.2-beta.12` and just used:
```
  private TargetState() {
    this.platform.log.debug(this.device.allowedModes);

    const TargetState = [4];
    TargetState.pop();
    if (this.device.allowedModes.includes('Cool')) {
      TargetState.push(this.platform.Characteristic.TargetHeatingCoolingState.COOL);
    }
    if (this.device.allowedModes.includes('Heat')) {
      TargetState.push(this.platform.Characteristic.TargetHeatingCoolingState.HEAT);
    }
    if (this.device.allowedModes.includes('Off')) {
      TargetState.push(this.platform.Characteristic.TargetHeatingCoolingState.OFF);
    }
    if (this.device.allowedModes.includes('Auto')) {
      TargetState.push(this.platform.Characteristic.TargetHeatingCoolingState.AUTO);
    }
    this.platform.log.debug('Only Show These Modes:', JSON.stringify(TargetState));
    return TargetState;
  }
```

**Comment by leemcx** [comment]
@donavanbecker, `v7.2.2-beta.12` is working as expected. Thank you.

**Comment by leemcx** [comment]
I've noticed that the versions I've tried (`v7.2.1-beta.6` and above) exhibit the same behaviours as explained in issue 'CurrentHeatingCoolingState not Updating #238'. This doesn't particularly bother me but I'm more than happy to troubleshoot this if that's something that interests you?

**Comment by donavanbecker** [comment]
@leemcx yeah if you can figure out what is causing this, I would more then happy implement this. Since it isn't a big issue, I haven't spent much time on it.

**Comment by donavanbecker** [comment]
Okay final beta should be out if you could test it.
@leemcx @ericingravity @snopas576

Beta Version: `v7.2.3-beta.0`

**Comment by leemcx** [comment]
All is working well as far as I can tell. The humidity report has been removed from the settings section of the HomeKit ui. I imagine that’s because my hardware doesn’t have a humidity sensor so this is a welcome addition. There is now an additional option in the ui that changes the unit between Celsius and Fahrenheit. This doesn’t appear to work for my setup, that may be because the hardware doesn’t support it. (We don’t use Fahrenheit in the UK). 

from Homebridge log:

`[HoneywellHome] Changing the Hardware Display Units from HomeKit is not supported.`

**Comment by donavanbecker** [comment]
@leemcx Are you saying your unit shows Fahrenheit and should be Celsius?

**Comment by leemcx** [comment]
@donavanbecker. No, sorry I wasn’t clear. I now have an option in the ui to change between Celsius and Fahrenheit. The default is Celsius and just from a testing point of view I tried to change it to Fahrenheit but it didn’t work.

**Comment by donavanbecker** [comment]
> @donavanbecker. No, sorry I wasn’t clear. I now have an option in the ui to change between Celsius and Fahrenheit. The default is Celsius and just from a testing point of view I tried to change it to Fahrenheit but it didn’t work.

Oh okay! Yeah I don't believe through the API this can be changed, so this was put into place to prevent any issues from happening.

It pulls the data from the API, just can't push that info to it.

**Comment by ericingravity** [comment]
Just getting around to this but I see 8.0.0 is out. I'll let you know if I find anything. Thanks for your work!
